name: flutter_another
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  image: ^2.0.4
  vector_math: ^2.0.8
  http: ^0.11.3+17
  tuple: ^1.0.2
  flutter:
    sdk: flutter
  audioplayers:
    path: ./audioplayer

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/resource/desc.json
    - assets/resource/Bosses.png
    - assets/resource/bos2.png
    - assets/resource/test2.png
    - assets/resource/block_destory.png
    - assets/resource/bomb1.png
    - assets/resource/explosion.png
    - assets/resource/gate.png
    - assets/resource/hero1.png
    - assets/resource/huaji90x90.png
    - assets/resource/monster_destory.png
    - assets/resource/sprite_bricks.png
    - assets/resource/sprite_bricks_solid.png
    - assets/resource/treasure.png
    - assets/resource/level/s1.png
    - assets/resource/level/s2.png
    - assets/resource/level/s3.png
    - assets/click.ogg
    - assets/powerup.ogg
    - assets/01_Title Screen.mp3
    - assets/02_Stage Start.mp3
    - assets/mario.mp3
    - assets/mario2.mp3
    - assets/mariogalaxy.mp3
    - assets/gameover.mp3
    - assets/LevelUp.mp3
    - assets/03_Stage Theme.mp3
    - assets/04_Find The Exit.mp3
    - assets/05_Stage Complete.mp3
    - assets/08_Life Lost.mp3
    - assets/bomb.ogg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
